/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and email a verification link.
         *
         *     The response is identical whether or not the address was already
         *     registered, so this endpoint cannot be used to discover who has an account.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for an access token and a refresh cookie.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate the refresh cookie and mint a new access token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Sign out of this device.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout All
         * @description Sign out of every device.
         */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Email
         * @description Confirm an email address and sign the user in.
         *
         *     Signing in here saves the user from typing their password again straight
         *     after clicking the link in their inbox.
         */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend Verification
         * @description Send another verification link.
         */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Email a password reset link.
         */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password
         * @description Set a new password, sign out other devices, and sign this one in.
         */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password of the signed-in account.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Org
         * @description Issue a new token pair scoped to another of the user's organizations.
         */
        post: operations["switch_org_api_v1_auth_switch_org_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The signed-in user with their memberships.
         *
         *     Returns a fresh access token so a client that has only the refresh cookie
         *     can bootstrap without a second call.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Start
         * @description Begin Google sign-in by redirecting the browser to Google.
         *
         *     ``redirect`` is where the SPA should land afterwards. Only same-site paths
         *     are accepted, so this cannot be turned into an open redirect.
         */
        get: operations["google_start_api_v1_auth_google_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google Callback
         * @description Complete Google sign-in and hand control back to the SPA.
         *
         *     The refresh cookie is set on the redirect response; the SPA then calls
         *     ``/auth/refresh`` to obtain its access token.
         */
        get: operations["google_callback_api_v1_auth_google_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update your profile
         * @description Change your display name or avatar.
         *
         *     The email address is not editable here: moving an account to a new address
         *     has to re-run verification.
         */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an organization
         * @description Create an organization; the caller becomes its first active admin.
         *
         *     The current access token does not carry the new organization. Refresh it
         *     before calling any `/orgs/current` endpoint, otherwise those requests are
         *     rejected as having no active organization.
         */
        post: operations["create_organization_api_v1_orgs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current org
         * @description Return the profile of the caller's active organization.
         */
        get: operations["read_current_organization_api_v1_orgs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the current org
         * @description Update the organization profile. Admin only; the slug never changes.
         */
        patch: operations["update_current_organization_api_v1_orgs_current_patch"];
        trace?: never;
    };
    "/api/v1/orgs/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List members
         * @description List the organization's members, oldest first.
         */
        get: operations["list_members_api_v1_orgs_current_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/current/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member
         * @description Remove a member. You may remove yourself unless you are the last admin.
         */
        delete: operations["remove_member_api_v1_orgs_current_members__user_id__delete"];
        options?: never;
        head?: never;
        /**
         * Change a member's role or status
         * @description Change a member's role or status.
         *
         *     You cannot change your own role, and the last active admin can be neither
         *     demoted nor disabled.
         */
        patch: operations["update_member_api_v1_orgs_current_members__user_id__patch"];
        trace?: never;
    };
    "/api/v1/orgs/current/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invitations
         * @description List every invitation ever sent for this organization, newest first.
         */
        get: operations["list_invitations_api_v1_orgs_current_invitations_get"];
        put?: never;
        /**
         * Invite someone
         * @description Email an invitation link.
         *
         *     Any live invitation for the same address is revoked and replaced, so
         *     re-inviting is always safe. Inviting an existing member is a conflict.
         */
        post: operations["create_invitation_api_v1_orgs_current_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/current/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend an invitation
         * @description Send a fresh link and extend the expiry. The previous link stops working.
         */
        post: operations["resend_invitation_api_v1_orgs_current_invitations__invitation_id__resend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/current/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an invitation
         * @description Revoke a pending invitation, invalidating its link immediately.
         */
        delete: operations["revoke_invitation_api_v1_orgs_current_invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview an invitation
         * @description Public: describe an invitation so the accept screen can be rendered.
         *
         *     Requires no authentication — the token is the credential. Returns only the
         *     organization's name, the inviter, the role and whether the invitee still
         *     needs to sign up.
         */
        get: operations["preview_invitation_api_v1_invitations__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation
         * @description Join the inviting organization as the signed-in user.
         *
         *     The signed-in address must match the invited one. Accepting twice is
         *     harmless and returns the existing membership. Obtain a new access token
         *     afterwards to make the new organization active.
         */
        post: operations["accept_invitation_api_v1_invitations__token__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenders
         * @description Search and filter the shared pool of notices.
         */
        get: operations["list_tenders_api_v1_tenders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tender Facets
         * @description Result counts per filter option, for the sidebar.
         */
        get: operations["tender_facets_api_v1_tenders_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenders/{tender_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tender
         * @description One notice with its extracted requirements, when they exist.
         */
        get: operations["get_tender_api_v1_tenders__tender_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Portals TenderSense ingests from, with their current health.
         */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description Every ingestion source with its full scraping configuration.
         */
        get: operations["list_sources_api_v1_admin_sources_get"];
        put?: never;
        /**
         * Create Source
         * @description Register a portal. ``adapter_key`` must match a known adapter.
         */
        post: operations["create_source_api_v1_admin_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_admin_sources__source_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Source
         * @description Remove a source and, by cascade, its tenders and raw documents.
         */
        delete: operations["delete_source_api_v1_admin_sources__source_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Source
         * @description Patch a source. Selector and endpoint changes are data, not a deploy.
         */
        patch: operations["update_source_api_v1_admin_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/tenders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Tender
         * @description Add one notice by hand, through the same upsert path the scrapers use.
         */
        post: operations["create_tender_api_v1_admin_tenders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tenders/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Tenders
         * @description Bulk import notices from a JSON array or a CSV document in the request body.
         *
         *     A malformed row is reported and skipped rather than failing the batch.
         */
        post: operations["import_tenders_api_v1_admin_tenders_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password?: string | null;
            /** New Password */
            new_password: string;
        };
        /**
         * EmailRequest
         * @description Used by resend-verification and forgot-password.
         */
        EmailRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResponse */
        ImportResponse: {
            /** Total */
            total: number;
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Unchanged */
            unchanged: number;
            /** Failed */
            failed: number;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        /** InvitationCreate */
        InvitationCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** @default member */
            role: components["schemas"]["OrgRole"];
        };
        /**
         * InvitationPreview
         * @description Public, unauthenticated view of an invitation.
         *
         *     Deliberately narrow: anyone holding the token can read this, so it exposes
         *     only what the accept screen needs and nothing else about the organization.
         */
        InvitationPreview: {
            /** Org Name */
            org_name: string;
            /** Inviter Name */
            inviter_name: string | null;
            role: components["schemas"]["OrgRole"];
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Requires Signup */
            requires_signup: boolean;
        };
        /** InvitationRead */
        InvitationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["OrgRole"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Invited By Name */
            invited_by_name: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "accepted" | "revoked" | "expired";
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MemberRead */
        MemberRead: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Avatar Url */
            avatar_url: string | null;
            role: components["schemas"]["OrgRole"];
            status: components["schemas"]["MembershipStatus"];
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** MemberUpdate */
        MemberUpdate: {
            role?: components["schemas"]["OrgRole"] | null;
            status?: components["schemas"]["MembershipStatus"] | null;
        };
        /**
         * MembershipStatus
         * @enum {string}
         */
        MembershipStatus: "active" | "disabled";
        /** MembershipSummary */
        MembershipSummary: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Org Name */
            org_name: string;
            /** Org Slug */
            org_slug: string;
            role: components["schemas"]["OrgRole"];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * OrgRole
         * @enum {string}
         */
        OrgRole: "admin" | "member";
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Website */
            website?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Timezone
             * @default Asia/Dhaka
             */
            timezone: string | null;
        };
        /** OrganizationRead */
        OrganizationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Country */
            country: string | null;
            /** Website */
            website: string | null;
            /** Description */
            description: string | null;
            /** Timezone */
            timezone: string;
            /** Plan */
            plan: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * OrganizationUpdate
         * @description Every field optional; fields left unset are not touched.
         */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Country */
            country?: string | null;
            /** Website */
            website?: string | null;
            /** Description */
            description?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** Page[MemberRead] */
        Page_MemberRead_: {
            /** Items */
            items?: components["schemas"]["MemberRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** Page[TenderSummary] */
        Page_TenderSummary_: {
            /** Items */
            items?: components["schemas"]["TenderSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ProcurementCategory
         * @enum {string}
         */
        ProcurementCategory: "goods" | "works" | "services" | "consulting" | "unknown";
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: boolean;
            /** Redis */
            redis: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * RegisterResponse
         * @description Registration does not sign the user in; they must verify first.
         */
        RegisterResponse: {
            user: components["schemas"]["UserRead"];
            /**
             * Verification Email Sent
             * @default true
             */
            verification_email_sent: boolean;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * SessionResponse
         * @description Returned by login, refresh, verify-email, reset-password and switch-org.
         *
         *     The refresh token is not in the body — it is set as an HttpOnly cookie.
         */
        SessionResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserRead"];
            /** Memberships */
            memberships?: components["schemas"]["MembershipSummary"][];
            /** Active Org Id */
            active_org_id?: string | null;
        };
        /** SourceAdminRead */
        SourceAdminRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Adapter Key */
            adapter_key: string;
            /** Base Url */
            base_url: string;
            /** Country */
            country?: string | null;
            /** Enabled */
            enabled: boolean;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /** Cursor */
            cursor?: {
                [key: string]: unknown;
            };
            health: components["schemas"]["SourceHealth"];
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
        };
        /** SourceCreate */
        SourceCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Adapter Key */
            adapter_key: string;
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /** Country */
            country?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
        };
        /**
         * SourceHealth
         * @enum {string}
         */
        SourceHealth: "ok" | "degraded" | "down";
        /** SourceRead */
        SourceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Enabled */
            enabled: boolean;
            health: components["schemas"]["SourceHealth"];
            /** Last Run At */
            last_run_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Consecutive Failures */
            consecutive_failures: number;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Name */
            name?: string | null;
            /** Adapter Key */
            adapter_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Country */
            country?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
        };
        /** SwitchOrgRequest */
        SwitchOrgRequest: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
        };
        /**
         * TenderCreate
         * @description A hand-entered notice. ``source_code`` picks the pool it lands in.
         */
        TenderCreate: {
            /** External Id */
            external_id: string;
            /** Canonical Url */
            canonical_url: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Procuring Entity */
            procuring_entity?: string | null;
            /** Country */
            country?: string | null;
            /** Procurement Method */
            procurement_method?: string | null;
            /** @default unknown */
            procurement_category: components["schemas"]["ProcurementCategory"];
            /** Published At */
            published_at?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Currency */
            currency?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            /** @default open */
            status: components["schemas"]["TenderStatus"];
            /** Language */
            language?: string | null;
            /** Portal Metadata */
            portal_metadata?: {
                [key: string]: unknown;
            };
            /**
             * Source Code
             * @default manual
             */
            source_code: string;
        };
        /** TenderCreateResponse */
        TenderCreateResponse: {
            /**
             * Tender Id
             * Format: uuid
             */
            tender_id: string;
            /** Outcome */
            outcome: string;
            /** Version */
            version: number;
        };
        /** TenderDetail */
        TenderDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Code */
            source_code: string;
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Procuring Entity */
            procuring_entity?: string | null;
            /** Country */
            country?: string | null;
            /** Procurement Method */
            procurement_method?: string | null;
            procurement_category: components["schemas"]["ProcurementCategory"];
            /** Published At */
            published_at?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Currency */
            currency?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            status: components["schemas"]["TenderStatus"];
            /** Canonical Url */
            canonical_url: string;
            /** Days To Deadline */
            days_to_deadline?: number | null;
            /** Description */
            description?: string | null;
            /** Language */
            language?: string | null;
            /** Portal Metadata */
            portal_metadata?: {
                [key: string]: unknown;
            };
            /** Version */
            version: number;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Extraction */
            extraction?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TenderFacets
         * @description Counts for the filter sidebar, so options can show their sizes.
         */
        TenderFacets: {
            /** By Source */
            by_source?: {
                [key: string]: number;
            };
            /** By Category */
            by_category?: {
                [key: string]: number;
            };
            /** By Country */
            by_country?: {
                [key: string]: number;
            };
            /** By Status */
            by_status?: {
                [key: string]: number;
            };
            /**
             * Closing Within 7 Days
             * @default 0
             */
            closing_within_7_days: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * TenderSortField
         * @description Columns a client may order by.
         *
         *     An allowlist rather than a free string: the value reaches an ORDER BY.
         * @enum {string}
         */
        TenderSortField: "published_at" | "deadline_at" | "title" | "estimated_value";
        /**
         * TenderStatus
         * @enum {string}
         */
        TenderStatus: "open" | "closed" | "cancelled" | "awarded" | "unknown";
        /**
         * TenderSummary
         * @description A row in a list. Deliberately narrow so listing stays cheap.
         */
        TenderSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Source Code */
            source_code: string;
            /** External Id */
            external_id: string;
            /** Title */
            title: string;
            /** Summary */
            summary?: string | null;
            /** Procuring Entity */
            procuring_entity?: string | null;
            /** Country */
            country?: string | null;
            /** Procurement Method */
            procurement_method?: string | null;
            procurement_category: components["schemas"]["ProcurementCategory"];
            /** Published At */
            published_at?: string | null;
            /** Deadline At */
            deadline_at?: string | null;
            /** Currency */
            currency?: string | null;
            /** Estimated Value */
            estimated_value?: number | null;
            status: components["schemas"]["TenderStatus"];
            /** Canonical Url */
            canonical_url: string;
            /** Days To Deadline */
            days_to_deadline?: number | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Email Verified */
            email_verified: boolean;
            /**
             * Has Password
             * @default true
             */
            has_password: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserUpdate
         * @description Every field optional; fields left unset are not touched.
         *
         *     Deliberately excludes ``email``: changing an address has to re-run
         *     verification, otherwise an account could be moved to an unproven address
         *     and inherit its organization's notifications.
         */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_org_api_v1_auth_switch_org_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    google_start_api_v1_auth_google_start_get: {
        parameters: {
            query?: {
                redirect?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_callback_api_v1_auth_google_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_api_v1_orgs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_current_organization_api_v1_orgs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
        };
    };
    update_current_organization_api_v1_orgs_current_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_v1_orgs_current_members_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MemberRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_v1_orgs_current_members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user account. */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_api_v1_orgs_current_members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the member's user account. */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invitations_api_v1_orgs_current_invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationRead"][];
                };
            };
        };
    };
    create_invitation_api_v1_orgs_current_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_invitation_api_v1_orgs_current_invitations__invitation_id__resend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the invitation. */
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_v1_orgs_current_invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id of the invitation. */
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_invitation_api_v1_invitations__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invitation_api_v1_invitations__token__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tenders_api_v1_tenders_get: {
        parameters: {
            query?: {
                /** @description Free-text search over title, summary and buyer */
                q?: string | null;
                /** @description Source codes */
                source?: string[] | null;
                /** @description ISO 3166-1 alpha-2 codes */
                country?: string[] | null;
                category?: components["schemas"]["ProcurementCategory"][] | null;
                status?: components["schemas"]["TenderStatus"][] | null;
                deadline_from?: string | null;
                deadline_to?: string | null;
                deadline_within_days?: number | null;
                /** @description Exclude closed and expired notices */
                open_only?: boolean;
                sort?: components["schemas"]["TenderSortField"];
                descending?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TenderSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tender_facets_api_v1_tenders_facets_get: {
        parameters: {
            query?: {
                /** @description Free-text search over title, summary and buyer */
                q?: string | null;
                /** @description Source codes */
                source?: string[] | null;
                /** @description ISO 3166-1 alpha-2 codes */
                country?: string[] | null;
                category?: components["schemas"]["ProcurementCategory"][] | null;
                status?: components["schemas"]["TenderStatus"][] | null;
                deadline_from?: string | null;
                deadline_to?: string | null;
                deadline_within_days?: number | null;
                /** @description Exclude closed and expired notices */
                open_only?: boolean;
                sort?: components["schemas"]["TenderSortField"];
                descending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderFacets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tender_api_v1_tenders__tender_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tender identifier */
                tender_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"][];
                };
            };
        };
    };
    list_sources_api_v1_admin_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdminRead"][];
                };
            };
        };
    };
    create_source_api_v1_admin_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_admin_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source identifier */
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_source_api_v1_admin_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source identifier */
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_v1_admin_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Source identifier */
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAdminRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tender_api_v1_admin_tenders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenderCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_tenders_api_v1_admin_tenders_import_post: {
        parameters: {
            query?: {
                /** @description Source code for rows that omit their own */
                source_code?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
