/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as HealthRouteImport } from './routes/health'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppDashboardRouteImport } from './routes/_app/app/dashboard'
import { Route as AppAppMatchesRouteImport } from './routes/_app/app/matches'
import { Route as AppAppNotificationsRouteImport } from './routes/_app/app/notifications'
import { Route as AppAppPipelineRouteImport } from './routes/_app/app/pipeline'
import { Route as AppAppTodayRouteImport } from './routes/_app/app/today'
import { Route as AppOnboardingIndexRouteImport } from './routes/_app/onboarding/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AppAppSettingsIndexRouteImport } from './routes/_app/app/settings/index'
import { Route as AppAppSettingsMembersRouteImport } from './routes/_app/app/settings/members'
import { Route as AppAppSettingsOrganizationRouteImport } from './routes/_app/app/settings/organization'
import { Route as AppAppSettingsProfileRouteImport } from './routes/_app/app/settings/profile'
import { Route as AppAppTendersIndexRouteImport } from './routes/_app/app/tenders/index'
import { Route as AppAppTendersTenderIdRouteImport } from './routes/_app/app/tenders/$tenderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDashboardRoute = AppAppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAppMatchesRoute = AppAppMatchesRouteImport.update({
  id: '/app/matches',
  path: '/app/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppAppNotificationsRoute = AppAppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPipelineRoute = AppAppPipelineRouteImport.update({
  id: '/app/pipeline',
  path: '/app/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTodayRoute = AppAppTodayRouteImport.update({
  id: '/app/today',
  path: '/app/today',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingIndexRoute = AppOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppSettingsIndexRoute = AppAppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSettingsMembersRoute = AppAppSettingsMembersRouteImport.update({
  id: '/app/settings/members',
  path: '/app/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppAppSettingsOrganizationRoute =
  AppAppSettingsOrganizationRouteImport.update({
    id: '/app/settings/organization',
    path: '/app/settings/organization',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppSettingsProfileRoute = AppAppSettingsProfileRouteImport.update({
  id: '/app/settings/profile',
  path: '/app/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTendersIndexRoute = AppAppTendersIndexRouteImport.update({
  id: '/app/tenders/',
  path: '/app/tenders/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTendersTenderIdRoute = AppAppTendersTenderIdRouteImport.update({
  id: '/app/tenders/$tenderId',
  path: '/app/tenders/$tenderId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/account': typeof AppAccountRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/matches': typeof AppAppMatchesRoute
  '/app/notifications': typeof AppAppNotificationsRoute
  '/app/pipeline': typeof AppAppPipelineRoute
  '/app/today': typeof AppAppTodayRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/app/': typeof AppAppIndexRoute
  '/onboarding/': typeof AppOnboardingIndexRoute
  '/app/settings/members': typeof AppAppSettingsMembersRoute
  '/app/settings/organization': typeof AppAppSettingsOrganizationRoute
  '/app/settings/profile': typeof AppAppSettingsProfileRoute
  '/app/tenders/$tenderId': typeof AppAppTendersTenderIdRoute
  '/app/settings/': typeof AppAppSettingsIndexRoute
  '/app/tenders/': typeof AppAppTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/account': typeof AppAccountRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/app/dashboard': typeof AppAppDashboardRoute
  '/app/matches': typeof AppAppMatchesRoute
  '/app/notifications': typeof AppAppNotificationsRoute
  '/app/pipeline': typeof AppAppPipelineRoute
  '/app/today': typeof AppAppTodayRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/app': typeof AppAppIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/app/settings/members': typeof AppAppSettingsMembersRoute
  '/app/settings/organization': typeof AppAppSettingsOrganizationRoute
  '/app/settings/profile': typeof AppAppSettingsProfileRoute
  '/app/tenders/$tenderId': typeof AppAppTendersTenderIdRoute
  '/app/settings': typeof AppAppSettingsIndexRoute
  '/app/tenders': typeof AppAppTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/health': typeof HealthRoute
  '/_app/account': typeof AppAccountRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/_app/app/dashboard': typeof AppAppDashboardRoute
  '/_app/app/matches': typeof AppAppMatchesRoute
  '/_app/app/notifications': typeof AppAppNotificationsRoute
  '/_app/app/pipeline': typeof AppAppPipelineRoute
  '/_app/app/today': typeof AppAppTodayRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/app/settings/members': typeof AppAppSettingsMembersRoute
  '/_app/app/settings/organization': typeof AppAppSettingsOrganizationRoute
  '/_app/app/settings/profile': typeof AppAppSettingsProfileRoute
  '/_app/app/tenders/$tenderId': typeof AppAppTendersTenderIdRoute
  '/_app/app/settings/': typeof AppAppSettingsIndexRoute
  '/_app/app/tenders/': typeof AppAppTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/invite/accept'
    | '/app/dashboard'
    | '/app/matches'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/today'
    | '/auth/google/callback'
    | '/app/'
    | '/onboarding/'
    | '/app/settings/members'
    | '/app/settings/organization'
    | '/app/settings/profile'
    | '/app/tenders/$tenderId'
    | '/app/settings/'
    | '/app/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/invite/accept'
    | '/app/dashboard'
    | '/app/matches'
    | '/app/notifications'
    | '/app/pipeline'
    | '/app/today'
    | '/auth/google/callback'
    | '/app'
    | '/onboarding'
    | '/app/settings/members'
    | '/app/settings/organization'
    | '/app/settings/profile'
    | '/app/tenders/$tenderId'
    | '/app/settings'
    | '/app/tenders'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/health'
    | '/_app/account'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/invite/accept'
    | '/_app/app/dashboard'
    | '/_app/app/matches'
    | '/_app/app/notifications'
    | '/_app/app/pipeline'
    | '/_app/app/today'
    | '/auth/google/callback'
    | '/_app/app/'
    | '/_app/onboarding/'
    | '/_app/app/settings/members'
    | '/_app/app/settings/organization'
    | '/_app/app/settings/profile'
    | '/_app/app/tenders/$tenderId'
    | '/_app/app/settings/'
    | '/_app/app/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  HealthRoute: typeof HealthRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/dashboard': {
      id: '/_app/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppAppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/matches': {
      id: '/_app/app/matches'
      path: '/app/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppAppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/notifications': {
      id: '/_app/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppAppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/pipeline': {
      id: '/_app/app/pipeline'
      path: '/app/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppAppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/today': {
      id: '/_app/app/today'
      path: '/app/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppAppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AppOnboardingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/settings/': {
      id: '/_app/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppAppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/settings/members': {
      id: '/_app/app/settings/members'
      path: '/app/settings/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppAppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/settings/organization': {
      id: '/_app/app/settings/organization'
      path: '/app/settings/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppAppSettingsOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/settings/profile': {
      id: '/_app/app/settings/profile'
      path: '/app/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppAppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/tenders/': {
      id: '/_app/app/tenders/'
      path: '/app/tenders'
      fullPath: '/app/tenders/'
      preLoaderRoute: typeof AppAppTendersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/tenders/$tenderId': {
      id: '/_app/app/tenders/$tenderId'
      path: '/app/tenders/$tenderId'
      fullPath: '/app/tenders/$tenderId'
      preLoaderRoute: typeof AppAppTendersTenderIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAppDashboardRoute: typeof AppAppDashboardRoute
  AppAppMatchesRoute: typeof AppAppMatchesRoute
  AppAppNotificationsRoute: typeof AppAppNotificationsRoute
  AppAppPipelineRoute: typeof AppAppPipelineRoute
  AppAppTodayRoute: typeof AppAppTodayRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppAppSettingsMembersRoute: typeof AppAppSettingsMembersRoute
  AppAppSettingsOrganizationRoute: typeof AppAppSettingsOrganizationRoute
  AppAppSettingsProfileRoute: typeof AppAppSettingsProfileRoute
  AppAppTendersTenderIdRoute: typeof AppAppTendersTenderIdRoute
  AppAppSettingsIndexRoute: typeof AppAppSettingsIndexRoute
  AppAppTendersIndexRoute: typeof AppAppTendersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAppDashboardRoute: AppAppDashboardRoute,
  AppAppMatchesRoute: AppAppMatchesRoute,
  AppAppNotificationsRoute: AppAppNotificationsRoute,
  AppAppPipelineRoute: AppAppPipelineRoute,
  AppAppTodayRoute: AppAppTodayRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppAppSettingsMembersRoute: AppAppSettingsMembersRoute,
  AppAppSettingsOrganizationRoute: AppAppSettingsOrganizationRoute,
  AppAppSettingsProfileRoute: AppAppSettingsProfileRoute,
  AppAppTendersTenderIdRoute: AppAppTendersTenderIdRoute,
  AppAppSettingsIndexRoute: AppAppSettingsIndexRoute,
  AppAppTendersIndexRoute: AppAppTendersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  HealthRoute: HealthRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
